# This workflow will build a docker container, publish and deploy it to Tencent Kubernetes Engine (TKE).
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Tencent Kubernetes Engine cluster, 
#    including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: 
#    - TENCENT_CLOUD_SECRET_ID with Tencent Cloud secret id
#    - TENCENT_CLOUD_SECRET_KEY with Tencent Cloud secret key 
#    - TENCENT_CLOUD_ACCOUNT_ID with Tencent Cloud account id
#    - TKE_REGISTRY_PASSWORD with TKE registry password
#
# 3. Change the values for the TKE_IMAGE_URL, TKE_REGION, TKE_CLUSTER_ID and DEPLOYMENT_NAME environment variables (below).
# https://hub.docker.com/r/teddysun/shadowsocks-r

name: shadowsocks-r

on:
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build
    - name: Create a configuration file
      run: |        
        mkdir -p /etc/shadowsocks-r
        cat > /etc/shadowsocks-r/config.json <<EOF
          {
              "server":"0.0.0.0",
              "server_ipv6":"::",
              "server_port":9000,
              "local_address":"127.0.0.1",
              "local_port":1080,
              "password":"env1r0nment",
              "timeout":120,
              "method":"aes-256-cfb",
              "protocol":"origin",
              "protocol_param":"",
              "obfs":"plain",
              "obfs_param":"",
              "redirect":"",
              "dns_ipv6":false,
              "fast_open":true,
              "workers":1
          }
          EOF

    - name: Start a container that listens on 9000
      run: |
        docker pull teddysun/shadowsocks-r
        docker run -d -p 9000:9000 -p 9000:9000/udp --name ssr --restart=always -v /etc/shadowsocks-r:/etc/shadowsocks-r teddysun/shadowsocks-r
